### ISSUE TITLE
ModuleNotFoundError: No module named 'cpp_mstar'

### ISSUE THREAD

**Issue by xycHhxx** [marmotlab/SCRIMP#1]
I‘m sorry to disturb you in your busy schedule. But when I run python3 setup.py build_ext --inplace, there is the following error：

**mstar_type_defs.hpp:8:10: fatal error: boost/graph/graph_traits.hpp: No such file or directory
    8 | #include <boost/graph/graph_traits.hpp>**

So I installed Boost=1.76.0，and finished compiling. However, when I run python3 and import cpp_mstar, the following error occurred：

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cpp_mstar'**

How to solve this problem?
Thanks for your kindness.

**Comment by ellemcfarlane** [comment]
Hi, not part of the team, but also trying to run this locally. Does it work if you do you "import od_mstar3.cpp_mstar", that worked for me when I ran into this issue!

**Comment by wyt2019suzhou** [comment]
Yes, should run 'import od_mstar3.cpp_mstar'. I have modified the README accordingly.  Thanks!

**Comment by ellemcfarlane** [comment]
Although, I tried the build & import again today with python 3.8 (instead of 3.7--not sure that's the key difference) and this time the direct import worked from top-level SCRIMP directory (i.e. git root dir):
```
(venv38) ~/SCRIMP
user1234 $ python3
Python 3.8.17 (default, Jun 14 2023, 17:49:30) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import od_mstar3
>>>
```
